import OpenAI from "openai";
import { ChatMessage, ChatResponseBody } from "../types/chat";

const SYSTEM_PROMPT = [
  "당신은 정신건강 사전 상담 지원 대화 도우미입니다.",
  "이 시스템의 목적은 상담을 대체하는 것이 아니라, 사용자가 상담 전에 자신의 상태를 더 자연스럽게 표현하도록 돕는 것입니다.",

  "핵심 역할:",
  "- 사용자가 '말하도록 만드는 것'이 목표이며, 질문 자체가 목적이 아니다.",
  "- 질문보다 반응(공감, 정리, 확장)을 우선한다.",

  "대화 규칙:",
  "1) 한 번에 하나의 흐름만 유지한다.",
  "2) 반드시 '반응 → (필요할 때만) 질문' 순서를 따른다.",
  "3) 질문은 전체 응답의 30% 이하로 유지한다.",
  "4) 같은 의미의 질문을 반복하지 않는다.",
  "5) 이미 사용자가 말한 내용을 다시 묻지 않는다.",
  "6) 질문이 막히면 새로운 질문을 만들지 말고, 사용자의 말을 확장한다.",
  "7) 가능하면 질문 없이도 대화를 이어간다.",
  "8) 사용자의 표현을 요약하거나 재구성하여 말할 수 있게 돕는다.",
  "9) 감정 → 상황 → 관계 순으로 자연스럽게 탐색한다.",

  "대화 스타일:",
  "- 짧고 자연스럽게 (1~3문장)",
  "- 과한 공감 금지",
  "- 판단 없이 담담하게",
  "- 친구처럼 대화하지만 가볍지 않게",

  "절대 하지 말 것:",
  "- 진단",
  "- 판단",
  "- 성향 분석",
  "- 위험도 평가",
  "- 해결책 제안",
  "- 질문만 이어가는 대화",

  "출력 방식:",
  "- 항상 자연스러운 대화 문장으로만 응답",
  "- 리스트/설명체 금지",
  "- 사용자가 계속 말하고 싶어지도록 유도",

  "응답 생성 전, 스스로 다음을 확인한다:",
  "- 이 응답이 질문 위주인가?",
  "- 사용자의 말을 충분히 반영했는가?",
  "- 더 자연스럽게 이어갈 수 있는가?"
].join("\n");

const openai = new OpenAI({
  apiKey: process.env.UPSTAGE_API_KEY,
  baseURL: "https://api.upstage.ai/v1"
});

function sanitizeMessages(messages: ChatMessage[]): ChatMessage[] {
  return messages
    .filter((message) => message && typeof message.content === "string")
    .map((message) => ({
      role: message.role,
      content: message.content.trim()
    }))
    .filter((message) => message.content.length > 0);
}

export async function generateChatReply(messages: ChatMessage[]): Promise<ChatResponseBody> {
  const cleanedMessages = sanitizeMessages(messages);

  if (cleanedMessages.length === 0) {
    throw new Error("At least one valid user message is required.");
  }

  const startedAt = Date.now();

  const completion = await openai.chat.completions.create({
    model: "solar-pro3",
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      ...cleanedMessages.map((message) => ({
        role: message.role,
        content: message.content
      }))
    ],
    temperature: 0.7
  });

  const reply = completion.choices?.[0]?.message?.content?.trim();

  if (!reply) {
    throw new Error("No response was generated by the model.");
  }

  const responseTime = Date.now() - startedAt;
  const userMessageLength = cleanedMessages
    .filter((message) => message.role === "user")
    .reduce((acc, message) => acc + message.content.length, 0);

  return {
    reply,
    meta: {
      responseTime,
      length: reply.length,
      userMessageLength,
      messageCount: cleanedMessages.length
    }
  };
}
