import OpenAI from "openai";
import { ChatMessage, ChatResponseBody } from "../types/chat";

const SYSTEM_PROMPT = [
  "당신은 정신건강 사전 상담 지원 대화 도우미입니다.",
  "이 시스템의 목적은 상담을 대체하는 것이 아니라, 사용자가 상담 전에 자신의 상태를 더 자연스럽게 표현하도록 돕는 것입니다.",
  "핵심 원칙:",
  "1) 사용자가 편하게 말할 수 있도록 긴장을 낮춘다.",
  "2) 평가받는 느낌 없이 대화를 이어간다.",
  "3) 질문은 한 번에 하나만, 취조처럼 느껴지지 않게 한다.",
  "4) 감정, 상황, 관계를 자연스럽게 끌어내되 사용자가 스스로 말하게 돕는다.",
  "5) 공감은 위로 자체가 아니라 표현을 촉진하기 위한 장치로 사용한다.",
  "6) 대화가 너무 벗어나면 부드럽게 중심으로 유도한다.",
  "7) 톤은 따뜻하지만 과하지 않게, 판단 없이 대화형으로 유지한다.",
  "절대 하지 말 것:",
  "- 진단",
  "- 판단",
  "- 성향 해석 (예: '~한 성향입니다')",
  "- 위험도 평가",
  "- 치료/해결책 제안",
  "반드시 사용자의 표현을 확장하고 구조화할 수 있는 짧고 자연스러운 응답을 생성하세요."
].join("\n");

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

function sanitizeMessages(messages: ChatMessage[]): ChatMessage[] {
  return messages
    .filter((message) => message && typeof message.content === "string")
    .map((message) => ({
      role: message.role,
      content: message.content.trim()
    }))
    .filter((message) => message.content.length > 0);
}

export async function generateChatReply(messages: ChatMessage[]): Promise<ChatResponseBody> {
  const cleanedMessages = sanitizeMessages(messages);

  if (cleanedMessages.length === 0) {
    throw new Error("At least one valid user message is required.");
  }

  const startedAt = Date.now();

  const completion = await openai.responses.create({
    model: process.env.OPENAI_MODEL || "gpt-4.1-mini",
    input: [
      { role: "system", content: SYSTEM_PROMPT },
      ...cleanedMessages.map((message) => ({
        role: message.role,
        content: message.content
      }))
    ],
    temperature: 0.7
  });

  const reply = completion.output_text?.trim();

  if (!reply) {
    throw new Error("No response was generated by the model.");
  }

  const responseTime = Date.now() - startedAt;
  const userMessageLength = cleanedMessages
    .filter((message) => message.role === "user")
    .reduce((acc, message) => acc + message.content.length, 0);

  return {
    reply,
    meta: {
      responseTime,
      length: reply.length,
      userMessageLength,
      messageCount: cleanedMessages.length
    }
  };
}
